name: CI - LHCI for PR URLs (supports localhost)

on:[push]

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
      GATSBY_CONCURRENT_DOWNLOAD: 1

    steps:
      - name: Extract URLs from PR body
        id: extract
        shell: bash
        run: |
          PR_BODY="${{ github.event.pull_request.body || '' }}"
          URLS=$(printf '%s\n' "$PR_BODY" | grep -Eo 'https?://[^[:space:)\]"\']+' || true)

          if [ -z "$URLS" ]; then
            echo "has_urls=false" >> $GITHUB_OUTPUT
            echo "has_localhost=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          ARGS=""
          ANY_LOCALHOST=false
          CLEANED_LIST=""

          for u in $URLS; do
            clean=$(echo "$u" | sed 's/[),.;:]*$//')
            ARGS="$ARGS --collect.url=$clean"
            CLEANED_LIST="$CLEANED_LIST$clean\n"
            if echo "$clean" | grep -E 'https?://(localhost|127\.0\.0\.1)(:[0-9]+)?' >/dev/null; then
              ANY_LOCALHOST=true
            fi
          done

          echo "ARGS=$ARGS" >> $GITHUB_ENV

          {
            echo "collected_urls<<EOF"
            printf '%b' "$CLEANED_LIST"
            echo "EOF"
          } >> $GITHUB_OUTPUT

          echo "has_urls=true" >> $GITHUB_OUTPUT
          if [ "$ANY_LOCALHOST" = true ]; then
            echo "has_localhost=true" >> $GITHUB_OUTPUT
          else
            echo "has_localhost=false" >> $GITHUB_OUTPUT
          fi

      - name: Show collected URLs (debug)
        if: steps.extract.outputs.has_urls == 'true'
        run: |
          echo "Collected URLs from PR body:"
          printf '%b\n' "${{ steps.extract.outputs.collected_urls || '' }}"

      - name: Checkout code (only if localhost URLs provided)
        if: steps.extract.outputs.has_localhost == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: npm install & build (only for localhost URLs)
        if: steps.extract.outputs.has_localhost == 'true'
        run: |
          npm ci
          npm run build

      - name: Start static server (only for localhost URLs)
        if: steps.extract.outputs.has_localhost == 'true'
        shell: bash
        run: |
          npx http-server ./public -p 9000 --silent &

          TIMEOUT=60
          START=0
          until curl -sSf http://localhost:9000/ >/dev/null; do
            sleep 1
            START=$((START+1))
            if [ $START -ge $TIMEOUT ]; then
              echo "Server did not start within ${TIMEOUT}s"
              exit 1
            fi
          done
          echo "Local server ready on http://localhost:9000/"

      - name: Run Lighthouse CI for supplied URLs
        if: steps.extract.outputs.has_urls == 'true'
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.15.x
          if [ -z "${ARGS}" ]; then
            echo "No ARGS found, nothing to run."
            exit 0
          fi
          echo "Running: lhci autorun $ARGS"
          eval "lhci autorun $ARGS"
