name: CI - LHCI for PR URLs (supports localhost)

on:
  pull_request:
    branches:
      - main

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
      GATSBY_CONCURRENT_DOWNLOAD: 1

    steps:
      - name: Extract URLs from PR body
        id: extract
        shell: bash
        run: |
          PR_BODY="${{ github.event.pull_request.body || '' }}"

          # find http(s) urls
          URLS=$(printf '%s\n' "$PR_BODY" | grep -Eo 'https?://[^[:space:)\]"\']+' || true)

          if [ -z "$URLS" ]; then
            echo "No URLs found in PR body."
            echo "has_urls=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          ARGS=""
          ANY_LOCALHOST=false
          CLEANED_LIST=""

          for u in $URLS; do
            # trim trailing punctuation
            clean=$(echo "$u" | sed 's/[),.;:]*$//')
            ARGS="$ARGS --collect.url=$clean"
            CLEANED_LIST="$CLEANED_LIST$clean\n"

            # detect localhost or 127.0.0.1
            if echo "$clean" | grep -E 'https?://(localhost|127\.0\.0\.1)(:[0-9]+)?' >/dev/null; then
              ANY_LOCALHOST=true
            fi
          done

          echo "ARGS=$ARGS" >> $GITHUB_ENV
          echo "collected_urls<<EOF" >> $GITHUB_OUTPUT
          echo -e "$CLEANED_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "has_urls=true" >> $GITHUB_OUTPUT
          if [ "$ANY_LOCALHOST" = true ]; then
            echo "has_localhost=true" >> $GITHUB_OUTPUT
          else
            echo "has_localhost=false" >> $GITHUB_OUTPUT
          fi

      - name: Show collected URLs (debug)
        if: steps.extract.outputs.has_urls == 'true'
        run: |
          echo "Collected URLs:"
          printf '%b\n' "${{ steps.extract.outputs.collected_urls || '' }}"

      - name: Checkout code
        if: steps.extract.outputs.has_localhost == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: npm install & build (only for localhost URLs)
        if: steps.extract.outputs.has_localhost == 'true'
        run: |
          npm ci
          npm run build

      - name: Start static server (only for localhost URLs)
        if: steps.extract.outputs.has_localhost == 'true'
        shell: bash
        run: |
          # Serve ./public on port 9000 (common for your config)
          # You can change the command/port if you serve differently.
          npx http-server ./public -p 9000 --silent &

          # Wait until server responds 200 or timeout after 60s
          TIMEOUT=60
          START=0
          until curl -sSf http://localhost:9000/ >/dev/null; do
            sleep 1
            START=$((START+1))
            if [ $START -ge $TIMEOUT ]; then
              echo "Server did not start within ${TIMEOUT}s"
              exit 1
            fi
          done
          echo "Local server ready on http://localhost:9000/"

      - name: Optional: validate each URL returns 200 (local or public)
        if: steps.extract.outputs.has_urls == 'true'
        run: |
          # check each URL for 200; non-200 will fail this step
          PR_URLS=$(printf '%s\n' "${{ steps.extract.outputs.collected_urls || '' }}" | sed '/^$/d')
          echo "$PR_URLS" | while read -r url; do
            echo "Checking $url"
            # Allow HEAD then GET fallback
            if ! curl -sSfI "$url" >/dev/null 2>&1; then
              # try full GET (some servers don't respond to HEAD)
              if ! curl -sSf "$url" >/dev/null 2>&1; then
                echo "URL $url is not reachable (non-200)."
                exit 1
              fi
            fi
          done

      - name: Run Lighthouse CI for supplied URLs
        if: steps.extract.outputs.has_urls == 'true'
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.15.x

          # ARGS exported earlier from extract step
          if [ -z "${ARGS}" ]; then
            echo "No ARGS found, nothing to run."
            exit 0
          fi

          echo "Running: lhci autorun $ARGS"
          eval "lhci autorun $ARGS"
